# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-01 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=32)),
            ],
        ),
    ]
