# Generated by Django 2.2 on 2020-06-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshops',
            name='book',
        ),
        migrations.AddField(
            model_name='books',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Bookshops'),
            preserve_default=False,
        ),
    ]
