# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180828_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Author')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book_author',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Book'),
        ),
    ]
